
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Miner.Config
{
public partial class MinerTables
{
    public TbHelloWorld TbHelloWorld {get; }
    public TbNihao TbNihao {get; }
    public TbSampleData TbSampleData {get; }

    public MinerTables(System.Func<string, ByteBuf> loader)
    {
        TbHelloWorld = new TbHelloWorld(loader("tbhelloworld"));
        TbNihao = new TbNihao(loader("tbnihao"));
        TbSampleData = new TbSampleData(loader("tbsampledata"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbHelloWorld.ResolveRef(this);
        TbNihao.ResolveRef(this);
        TbSampleData.ResolveRef(this);
    }
}

}
