
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Miner.Config
{
public partial class TbHelloWorld
{
    private readonly System.Collections.Generic.Dictionary<int, HelloWorld> _dataMap;
    private readonly System.Collections.Generic.List<HelloWorld> _dataList;
    
    public TbHelloWorld(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, HelloWorld>(n);
        _dataList = new System.Collections.Generic.List<HelloWorld>(n);
        for(int i = n ; i > 0 ; --i)
        {
            HelloWorld _v;
            _v = global::Miner.Config.HelloWorld.DeserializeHelloWorld(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, HelloWorld> DataMap => _dataMap;
    public System.Collections.Generic.List<HelloWorld> DataList => _dataList;

    public HelloWorld GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public HelloWorld Get(int key) => _dataMap[key];
    public HelloWorld this[int key] => _dataMap[key];

    public void ResolveRef(MinerTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

