
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Miner.Config
{
public partial class TbNihao
{
    private readonly System.Collections.Generic.Dictionary<int, Nihao> _dataMap;
    private readonly System.Collections.Generic.List<Nihao> _dataList;
    
    public TbNihao(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Nihao>(n);
        _dataList = new System.Collections.Generic.List<Nihao>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Nihao _v;
            _v = global::Miner.Config.Nihao.DeserializeNihao(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Nihao> DataMap => _dataMap;
    public System.Collections.Generic.List<Nihao> DataList => _dataList;

    public Nihao GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Nihao Get(int key) => _dataMap[key];
    public Nihao this[int key] => _dataMap[key];

    public void ResolveRef(MinerTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

