
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Miner.Config
{
public partial class TbSampleData
{
    private readonly System.Collections.Generic.Dictionary<int, SampleData> _dataMap;
    private readonly System.Collections.Generic.List<SampleData> _dataList;
    
    public TbSampleData(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, SampleData>(n);
        _dataList = new System.Collections.Generic.List<SampleData>(n);
        for(int i = n ; i > 0 ; --i)
        {
            SampleData _v;
            _v = global::Miner.Config.SampleData.DeserializeSampleData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SampleData> DataMap => _dataMap;
    public System.Collections.Generic.List<SampleData> DataList => _dataList;

    public SampleData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SampleData Get(int key) => _dataMap[key];
    public SampleData this[int key] => _dataMap[key];

    public void ResolveRef(MinerTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

