using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Miner.Config.Editor
{
    public static class MinerTablesAsyncGenerator
    {
        private const string TablesTypeName = "Miner.Config.MinerTables";
        private const string GeneratedPath = "Assets/LubanConfig/Generated/MinerTables.Async.cs";
        internal const string TablesSourcePath = "Assets/LubanConfig/CSharp/MinerTables.cs";

        [MenuItem("工具/Luban/生成异步接口")]
        public static void GenerateAsyncTables()
        {
            string[] fileNames;
            if (TryGetTablesType(out var tablesType))
            {
                var properties = tablesType.GetProperties()
                    .Where(p => p.GetGetMethod() != null)
                    .Select(p => p.Name.ToLowerInvariant())
                    .ToArray();

                if (properties.Length == 0)
                {
                    Debug.LogWarning("[Luban] MinerTables 未包含任何表属性，跳过生成。");
                    return;
                }

                fileNames = properties;
            }
            else
            {
                if (!TryGetFileNamesFromSource(out fileNames))
                {
                    Debug.LogError($"[Luban] 未找到类型 {TablesTypeName}，且无法从源码解析表名。");
                    return;
                }
            }

            var content = BuildContent(fileNames);
            WriteIfChanged(GeneratedPath, content);
        }

        private static bool TryGetTablesType(out Type tablesType)
        {
            tablesType = null;
            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                tablesType = asm.GetType(TablesTypeName);
                if (tablesType != null)
                {
                    return true;
                }
            }
            return false;
        }

        private static bool TryGetFileNamesFromSource(out string[] fileNames)
        {
            fileNames = Array.Empty<string>();

            if (!File.Exists(TablesSourcePath))
            {
                return false;
            }

            var lines = File.ReadAllLines(TablesSourcePath);
            var list = lines
                .Select(line => ExtractLoaderName(line))
                .Where(name => !string.IsNullOrEmpty(name))
                .Distinct()
                .ToArray();

            if (list.Length == 0)
            {
                return false;
            }

            fileNames = list;
            return true;
        }

        private static string ExtractLoaderName(string line)
        {
            const string marker = "loader(\"";
            var idx = line.IndexOf(marker, StringComparison.Ordinal);
            if (idx < 0)
            {
                return null;
            }

            idx += marker.Length;
            var end = line.IndexOf("\"", idx, StringComparison.Ordinal);
            if (end < 0)
            {
                return null;
            }

            return line.Substring(idx, end - idx);
        }

        private static string BuildContent(string[] fileNames)
        {
            var sb = new StringBuilder();
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by MinerTablesAsyncGenerator.");
            sb.AppendLine("//     Changes to this file may be overwritten.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine("using Luban;");
            sb.AppendLine();
            sb.AppendLine("namespace Miner.Config");
            sb.AppendLine("{");
            sb.AppendLine("    public partial class MinerTables");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 异步创建配置表（热更模式）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"loader\">异步加载函数，参数为不含后缀的表名</param>");
            sb.AppendLine("        public static async UniTask<MinerTables> CreateAsync(System.Func<string, UniTask<ByteBuf>> loader)");
            sb.AppendLine("        {");
            sb.AppendLine("            var cache = new Dictionary<string, ByteBuf>();");
            sb.AppendLine();
            sb.AppendLine("            var fileNames = new[]");
            sb.AppendLine("            {");
            foreach (var name in fileNames)
            {
                sb.AppendLine($"                \"{name}\",");
            }
            sb.AppendLine("            };");
            sb.AppendLine();
            sb.AppendLine("            foreach (var fileName in fileNames)");
            sb.AppendLine("            {");
            sb.AppendLine("                cache[fileName] = await loader(fileName);");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return new MinerTables(fileName =>");
            sb.AppendLine("            {");
            sb.AppendLine("                if (cache.TryGetValue(fileName, out var buf))");
            sb.AppendLine("                {");
            sb.AppendLine("                    return buf;");
            sb.AppendLine("                }");
            sb.AppendLine("                return new ByteBuf(new byte[0]);");
            sb.AppendLine("            });");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void WriteIfChanged(string path, string content)
        {
            var fullPath = Path.GetFullPath(path);
            var dir = Path.GetDirectoryName(fullPath);
            if (!Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir ?? string.Empty);
            }

            if (File.Exists(fullPath))
            {
                var existing = File.ReadAllText(fullPath);
                if (existing == content)
                {
                    Debug.Log("[Luban] 异步接口已是最新，无需更新");
                    return;
                }
            }

            File.WriteAllText(fullPath, content, new UTF8Encoding(true));
            AssetDatabase.ImportAsset(path);
            Debug.Log($"[Luban] 异步接口已生成: {path}");
        }

    }

    [InitializeOnLoad]
    public static class MinerTablesAsyncGeneratorAutoRunner
    {
        static MinerTablesAsyncGeneratorAutoRunner()
        {
            // Unity 启动或脚本刷新时，确保异步接口存在
            EditorApplication.delayCall += () =>
            {
                if (File.Exists(MinerTablesAsyncGenerator.TablesSourcePath))
                {
                    MinerTablesAsyncGenerator.GenerateAsyncTables();
                }
            };
        }
    }

    public class MinerTablesPostprocessor : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
        {
            if (importedAssets.Any(p => p.Replace("\\", "/") == MinerTablesAsyncGenerator.TablesSourcePath))
            {
                MinerTablesAsyncGenerator.GenerateAsyncTables();
            }
        }
    }
}
