
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Miner.Config.sample
{ 
    public enum ESampleQuality
    {
        /// <summary>
        /// 普通
        /// </summary>
        COMMON = 1,
        /// <summary>
        /// 稀有
        /// </summary>
        RARE = 2,
        /// <summary>
        /// 史诗
        /// </summary>
        EPIC = 3,
        /// <summary>
        /// 传说
        /// </summary>
        LEGENDARY = 4,
    }

} 

