
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Miner.Config.sample
{ 
    public enum ESampleType
    {
        /// <summary>
        /// 类型A
        /// </summary>
        TYPE_A = 1,
        /// <summary>
        /// 类型B
        /// </summary>
        TYPE_B = 2,
        /// <summary>
        /// 类型C
        /// </summary>
        TYPE_C = 3,
        /// <summary>
        /// 类型D
        /// </summary>
        TYPE_D = 4,
    }

} 

