
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Miner.Config.sample
{
public sealed partial class SampleData : Luban.BeanBase
{
    public SampleData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Type = (sample.ESampleType)_buf.ReadInt();
        Quality = (sample.ESampleQuality)_buf.ReadInt();
        Value1 = _buf.ReadInt();
        Value2 = _buf.ReadInt();
        Price = _buf.ReadInt();
        Description = _buf.ReadString();
    }

    public static SampleData DeserializeSampleData(ByteBuf _buf)
    {
        return new sample.SampleData(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly sample.ESampleType Type;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly sample.ESampleQuality Quality;
    /// <summary>
    /// 数值1
    /// </summary>
    public readonly int Value1;
    /// <summary>
    /// 数值2
    /// </summary>
    public readonly int Value2;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -1328534696;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(MinerTables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "quality:" + Quality + ","
        + "value1:" + Value1 + ","
        + "value2:" + Value2 + ","
        + "price:" + Price + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

